#!/bin/sh

rm -f LFS_*img

rm f_*lua

./encap_file.pl *.html *.ico

docker run --dns=8.8.8.8 --rm -ti -v ~/nodemcu-firmware:/opt/nodemcu-firmware -v `pwd`:/opt/lua marcelstoer/nodemcu-build lfs-image

mv -f LFS_f*img lfs.img

